import {
  registerPlugin,
  unregisterPlugin,
  getPlugins,
  clearPlugins,
  applySnapshotPlugins,
  applyRoutePlugins,
  applyReportPlugins,
  Plugin,
} from './plugin';
import { RouteSnapshot, Route } from './types';

const baseSnapshot = (): RouteSnapshot => ({
  id: 'snap1',
  timestamp: '2024-01-01T00:00:00Z',
  source: 'http://localhost:3000',
  routes: [],
});

const route = (method: string, path: string): Route => ({ method, path });

beforeEach(() => clearPlugins());

test('registers and retrieves plugins', () => {
  const p: Plugin = { name: 'test-plugin' };
  registerPlugin(p);
  expect(getPlugins()).toHaveLength(1);
  expect(getPlugins()[0].name).toBe('test-plugin');
});

test('throws on duplicate registration', () => {
  registerPlugin({ name: 'dup' });
  expect(() => registerPlugin({ name: 'dup' })).toThrow('already registered');
});

test('unregisters plugin', () => {
  registerPlugin({ name: 'rem' });
  expect(unregisterPlugin('rem')).toBe(true);
  expect(getPlugins()).toHaveLength(0);
});

test('unregister returns false for unknown plugin', () => {
  expect(unregisterPlugin('nope')).toBe(false);
});

test('applySnapshotPlugins transforms snapshot', () => {
  registerPlugin({
    name: 'snap-plugin',
    onSnapshot: ({ snapshot }) => ({ ...snapshot, source: 'modified' }),
  });
  const result = applySnapshotPlugins({ snapshot: baseSnapshot(), routes: [] });
  expect(result.source).toBe('modified');
});

test('applyRoutePlugins filters routes', () => {
  registerPlugin({
    name: 'route-filter',
    onRoutes: (routes) => routes.filter(r => r.method === 'GET'),
  });
  const routes = [route('GET', '/a'), route('POST', '/b')];
  const result = applyRoutePlugins(routes);
  expect(result).toHaveLength(1);
  expect(result[0].method).toBe('GET');
});

test('applyReportPlugins transforms report string', () => {
  registerPlugin({
    name: 'report-plugin',
    onReport: (r) => r + '\n<!-- generated by plugin -->',
  });
  const result = applyReportPlugins('# Report');
  expect(result).toContain('generated by plugin');
});

test('multiple plugins apply in order', () => {
  registerPlugin({ name: 'p1', onReport: (r) => r + ' p1' });
  registerPlugin({ name: 'p2', onReport: (r) => r + ' p2' });
  expect(applyReportPlugins('base')).toBe('base p1 p2');
});
